--liquibase formatted sql
--changeset me:V1.0-init.sql

CREATE TABLE USERS(
    USERNAME VARCHAR PRIMARY KEY,
    PASSWORD VARCHAR NOT NULL,
    ROLES VARCHAR NOT NULL,
    EXPIRED BOOLEAN NOT NULL,
    LOCKED BOOLEAN NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    ENTITY_VERSION BIGINT NOT NULL
);

CREATE TABLE NOTIFICATIONS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR NOT NULL,
    MESSAGE VARCHAR NOT NULL,
    CREATED_TIMESTAMP BIGINT NOT NULL,
    ENTITY_VERSION BIGINT NOT NULL
);