--liquibase formatted sql
--changeset me:V1.0-init.sql

CREATE TABLE USERS(
    USERNAME VARCHAR PRIMARY KEY,
    PASSWORD VARCHAR NOT NULL,
    ROLES VARCHAR NOT NULL,
    EXPIRED BOOLEAN NOT NULL,
    LOCKED BOOLEAN NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    ENTITY_VERSION BIGINT NOT NULL
);